version: '3'
services:
  # 普通のWEBサーバ
  app:
    image: php:apache
    container_name: app
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www/html

  # 攻撃者が管理するWEBサーバ
  evil_app:
    image: httpd:alpine
    container_name: evil_app
    ports:
      - "8002:80"
    depends_on: 
      - app
    volumes:
      - ./evil_app:/usr/local/apache2/htdocs/
  
  # 攻撃者が窃取した情報を受け取るサーバ
  capture:
    image: python:alpine
    container_name: capture
    working_dir: /home
    command: python -m http.server 80
    ports:
      - "8003:80"